

name: saloonclassifier
description: Saloon Classifier in Flutter using TensorFlow Lite
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  image: ^3.0.2
  collection: ^1.17.1
  


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios : true 
  image_path : assets/logo.png
flutter:
  uses-material-design: true

  fonts:  
  - family: SquadaOne
    fonts:
      - asset: assets/SquadaOne-Regular.ttf
  - family: ContrailOne
    fonts:
      - asset: assets/ContrailOne-Regular.ttf
  - family: Roboto
    fonts:
      - asset: assets/Roboto-Light.ttf      
  
  assets:
    - assets/
    
